### ISSUE TITLE
Plugins directory?

### ISSUE THREAD

**Issue by redBaronNc** [wejs/we-plugin#1]
Hello,
Can you clarify where the plugin files should be put? in the readme you only describe the file structure of a plugin but you don't indicate where the plugin folder should be.

**Comment by albertosouza** [comment]
@redBaronNc use this config in one of your sails.js config files:
```js
      npmModules: {
        // regex for check if a package is one we module
        // Ex.: we-plugin-user
        packagesNameRegex: /^we-plugin-/,
        packagesFolder: null
      }
```

By default this npm module loads all projects starting with ```we-plugin-``` .

OBS.: this is only for sails.js, i am working in we.js v0.3 how dont use sails.js and has a plugin feature in core

**Comment by redBaronNc** [comment]
Thanks for your help, I will try it :-)

**Comment by redBaronNc** [comment]
It looks like there is an error in your code in file npmModuleLoader.js

line 182
    /**
     * Get npm modules folder
     *
     */
    getNpmModulesFolder: function getNpmModulesFolder(sails) {
      if (sails.config.packagesFolder)
        return sails.config.packagesFolder;
      return sails.config.appPath + '/node_modules';
    },
"sails.config.packagesFolder "
should be replaced by
"sails.config.npmModules.packagesFolder"
Otherwise the config you define is not taken into account for packagesFolder.

**Comment by albertosouza** [comment]
Sure, 

i changed the default config in master branch, you can now test

**Comment by redBaronNc** [comment]
I get a new error. Here is my config:
module.exports.npmModules = {
	// regex for check if a package is one we module
	// Ex.: we-plugin-user
	packagesNameRegex: /^plugin-/,
	packagesFolder: '/fullpath/plugins'
};

in the plugins directory I have a plugin-user folder containing the structure you described.

Here is the error I get:

Error: Cannot find module '../plugins/plugin-user'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at .../node_modules/we-plugin/lib/npmModuleLoader.js:203:39
    at Object.oncomplete (fs.js:107:15)

Is there any mandatory file in the plugin folder to make it a valid plugin?

**Comment by albertosouza** [comment]
@redBaronNc use this auth plugin as example: https://github.com/wejs/we-plugin-auth
